version: "3.7"

services:
  mongo:
    image: mongo:4.2
    container_name: mongo_container
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin_mongo
      - MONGO_INITDB_DATABASE=data
      - MONGO_INITDB_ROOT_PASSWORD=pass_mongo
    networks: 
      - app-network
    ports:
      - '27017:27017'
    volumes: 
      - ./mongodb:/data/db
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express_container
    restart: always
    depends_on:
      - mongo
    networks: 
      - app-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin_mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass_mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin_web
      - ME_CONFIG_BASICAUTH_PASSWORD=pass_web
    ports:
      - '8081:8081'

networks:
  app-network:
    driver: bridge