version: '3.7'
services:
  redis:
    container_name: redis
    restart: always
    # hostname: redis # opcional, se não for definido, o container name será usado
    image: redis

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8080:8081"